spring.application.name=ms-productor
server.port=8080
spring.profiles.active=local

# Azure AD B2C
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/5219c13e-f4f0-42b5-b8a5-389b6b873538/v2.0
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://sisinsc.b2clogin.com/sisinsc.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_sign_up_sign_in

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Oracle Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
oracle.net.wallet_location=${WALLET_PATH:src/main/resources/wallet}

# AWS S3
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.sessionToken=${AWS_SESSION_TOKEN}
aws.region=us-east-1
aws.s3.bucketName=${S3_BUCKET_NAME}
